In [1]:
import pandas as pd
import numpy as np

data1 = {
    'Tid': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Refund': ['Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No'],
    'Marital Status': ['Single', 'Married', 'Single', 'Married', 'Divorced', 'Married', 'Divorced', 'Single', 'Married', 'Single'],
    'Taxable Income': ['125K', '100K', '70K', '120K', '95K', '60K', '220K', '85K', '75K', '90K'],
    'Cheat': ['No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes']
}

df1 = pd.DataFrame(data1)
display(df1)

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
1    2     No        Married           100K    No
2    3     No         Single            70K    No
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No
9   10     No         Single            90K   Yes

In [2]:
rows_located = df1.iloc[[0, 4, 7, 8]]
display(rows_located)

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
4    5     No       Divorced            95K   Yes
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No

In [3]:
# 1. Select row from index 3 to 7 (inclusive of 7)
task_1 = df1.iloc[3:8]
print("--- Rows 3 to 7 ---")
display(task_1)

# 2. Select row from index 4 to 8, and column 2 to 4 (inclusive bounds)
task_2 = df1.iloc[4:9, 2:5]
print("\n--- Rows 4 to 8, Columns 2 to 4 ---")
display(task_2)

# 3. Select all rows with column index 1 to 3 (include index 3 during selection)
task_3 = df1.iloc[:, 1:4]
print("\n--- All rows, Columns 1 to 3 ---")
display(task_3)

--- Rows 3 to 7 ---

   Tid Refund Marital Status Taxable Income Cheat
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes

--- Rows 4 to 8, Columns 2 to 4 ---

  Marital Status Taxable Income Cheat
4       Divorced            95K   Yes
5        Married            60K    No
6       Divorced           220K    No
7         Single            85K   Yes
8        Married            75K    No

--- All rows, Columns 1 to 3 ---

  Refund Marital Status Taxable Income
0    Yes         Single           125K
1     No        Married           100K
2     No         Single            70K
3    Yes        Married           120K
4     No       Divorced            95K
5     No        Married            60K
6    Yes       Divorced           220K
7     No         Single            85K
8     No        Married            75K
9     No         Single            90K

In [4]:
# Read the downloaded csv file and display the first five rows
try:
    df_iris = pd.read_csv('Iris.csv')
    display(df_iris.head())
except FileNotFoundError:
    print("Please ensure 'Iris.csv' is downloaded and in the same directory.")

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
# Delete row 4 (index 4) and delete column 3 (index 3)
if 'df_iris' in locals():
    # .drop() for index, and extracting the column name by index to drop it
    col_name = df_iris.columns[3]
    df_iris_modified = df_iris.drop(index=4).drop(columns=[col_name])
    
    print(f"Dropped row 4 and column '{col_name}' (index 3).")
    display(df_iris_modified.head())

Dropped row 4 and column 'PetalLengthCm' (index 3).

   Id  SepalLengthCm  SepalWidthCm  PetalWidthCm      Species
0   1            5.1           3.5           0.2  Iris-setosa
1   2            4.9           3.0           0.2  Iris-setosa
2   3            4.7           3.2           0.2  Iris-setosa
3   4            4.6           3.1           0.2  Iris-setosa
5   6            5.4           3.9           0.4  Iris-setosa

In [6]:
# Create the sample dataset
data2 = {
    'Employee_ID': [101, 102, 103, 104, 105],
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Edward'],
    'Department': ['HR', 'IT', 'IT', 'Marketing', 'Sales'],
    'Age': [29, 34, 41, 28, 38],
    'Salary': [50000, 70000, 65000, 55000, 60000],
    'Years_of_Experience': [4, 8, 10, 3, 12],
    'Joining_Date': ['2020-03-15', '2017-07-19', '2013-06-01', '2021-02-10', '2010-11-25'],
    'Gender': ['Female', 'Male', 'Male', 'Female', 'Male'],
    'Bonus': [5000, 7000, 6000, 4500, 5000],
    'Rating': [4.5, 4.0, 3.8, 4.7, 3.5]
}

pd.DataFrame(data2).to_csv('employees.csv', index=False)
df_emp = pd.read_csv('employees.csv')

# a) Shape (number of rows and columns)
print(f"a) Shape of DataFrame: {df_emp.shape}\n")

# b) Summary (data types and non-null counts)
print("b) Summary of DataFrame:")
df_emp.info()
print("\n")

# c) Generate descriptive statistics
print("c) Descriptive Statistics:")
display(df_emp.describe())

# d) First 5 rows and last 3 rows
print("\nd) First 5 rows:")
display(df_emp.head())
print("\nLast 3 rows:")
display(df_emp.tail(3))

# e) Calculate specific statistics
print("\ne) Calculated Statistics:")
print(f"  i. Average salary: {df_emp['Salary'].mean()}")
print(f" ii. Total bonus: {df_emp['Bonus'].sum()}")
print(f"iii. Youngest employee's age: {df_emp['Age'].min()}")
print(f" iv. Highest performance rating: {df_emp['Rating'].max()}")

# f) Sort by Salary in descending order
print("\nf) Sorted by Salary (Descending):")
display(df_emp.sort_values(by='Salary', ascending=False))

# g) Add Performance Category column
conditions = [
    (df_emp['Rating'] >= 4.5),
    (df_emp['Rating'] >= 4.0) & (df_emp['Rating'] < 4.5),
    (df_emp['Rating'] < 4.0)
]
choices = ['Excellent', 'Good', 'Average']
df_emp['Performance_Category'] = np.select(conditions, choices)

# h) Identify missing values
print("\nh) Missing values in each column:")
print(df_emp.isnull().sum())

# i) Rename Employee_ID to ID
df_emp.rename(columns={'Employee_ID': 'ID'}, inplace=True)

# j) Find employees with >5 years experience AND in IT department
print("\nj) Employees with >5 years experience AND in IT:")
target_employees = df_emp[(df_emp['Years_of_Experience'] > 5) & (df_emp['Department'] == 'IT')]
display(target_employees)

# k) Add Tax column (10% of Salary)
df_emp['Tax'] = df_emp['Salary'] * 0.10

# Display final modified DataFrame before saving
print("\nFinal Modified DataFrame (with new columns):")
display(df_emp)

# l) Save modified DataFrame to a new CSV file
df_emp.to_csv('employees_modified.csv', index=False)
print("\nl) Modified DataFrame successfully saved to 'employees_modified.csv'")

a) Shape of DataFrame: (5, 10)

b) Summary of DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes


c) Descriptive Statistics:

,Employee_ID,Age,Salary,Years_of_Experience,Bonus,Rating
count,5.000000,5.000000,5.00000,5.000000,5.0,5.000000
mean,103.000000,34.000000,60000.00000,7.400000,5500.0,4.100000
std,1.581139,5.612486,7905.69415,3.847077,1000.0,0.494975
min,101.000000,28.000000,50000.00000,3.000000,4500.0,3.500000
25%,102.000000,29.000000,55000.00000,4.000000,5000.0,3.800000
50%,103.000000,34.000000,60000.00000,8.000000,5000.0,4.000000
75%,104.000000,38.000000,65000.00000,10.000000,6000.0,4.500000
max,105.000000,41.000000,70000.00000,12.000000,7000.0,4.700000

d) First 5 rows:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

Last 3 rows:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

e) Calculated Statistics:
  i. Average salary: 60000.0
 ii. Total bonus: 27500
iii. Youngest employee's age: 28
 iv. Highest performance rating: 4.7

f) Sorted by Salary (Descending):

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5

h) Missing values in each column:
Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance_Category    0
dtype: int64

j) Employees with >5 years experience AND in IT:

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average

Final Modified DataFrame (with new columns):

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category,Tax
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent,5000.0
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,6500.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent,5500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average,6000.0

l) Modified DataFrame successfully saved to 'employees_modified.csv'